name: 问题反馈
description: 使用过程中遇到的错误或不合理功能
labels: [ "bug" ]
title: "[BUG] "
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 提问题前请检查
      description: 确认问题依然存在
      options:
        - label: 已检查过问题列表，没有人提过相同问题
          required: true
        - label: 软件的最新版本依然没有被修复
          required: true

  - type: input
    id: version
    attributes:
      label: 软件版本
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: 电视品牌
    validations:
      required: true

  - type: input
    id: android
    attributes:
      label: Android版本
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: 问题描述
      description: 请描述下问题的具体细节
      placeholder: |
        1. 错误表现
        2. 如何复现
        3. 想法建议
    validations:
      required: true

